version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: docker
  directory: /integration
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /internal/witness/cmd/feeder
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /internal/witness/cmd/witness
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /trillian/examples/deployment/docker/ctfe
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /trillian/examples/deployment/docker/envsubst
  schedule:
    interval: daily
